# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: wallet_db
    ports: 
      - "3306:3306" # No need to expose port when in production to keep the db private within net
    volumes:
      - db-data:/var/lib/mysql

  wallet-service-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    environment:
      - USER=root
      - PASSWORD=my-secret-pw
      - DB_NAME=wallet_db
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db

volumes:
  db-data:
    driver: local