name: Build 
on: push

env:
  IMAGE_NAME: wallet-service-api

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install modules
      run: npm ci
    - name: Run unit tests
      run: npm run test:unit
    - name: Run unit test:cov
      run: npm run unit-test:cov
    - name: Publish Unit-Test Report
      uses: mikepenz/action-junit-report@v3
      if: success() || failure() # always run even if the previous step fails
      with:
        report_paths: 'unit-test-result/*.xml'
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}

      
